services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    networks:
      - agent-network
    volumes:
      - ollama-data:/root/.ollama
  
  chat-api:
    env_file:
      - .env
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_BASE_URL=${MODEL_BASE_URL}
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - agent-network
    depends_on:
      - ollama

networks:
  agent-network:
    external: true
volumes:
  ollama-data: